# Generated by Django 2.2.9 on 2020-02-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
